# This workflow will install the required gems using Bundler to optimize dependency management

name: Build IPA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install Dependencies
      run: |
        echo "source 'https://rubygems.org'" > Gemfile
        echo "gem 'fastlane', '~> 2.212.0'" >> Gemfile
        echo "gem 'rubyzip', '~> 2.3.0'" >> Gemfile
        bundle install

    - name: Verify Fastlane
      run: bundle exec fastlane --version

    - name: Build IPA
      run: bundle exec fastlane build