# This is a sample GitHub Actions workflow file for building an iOS IPA
name: Build IPA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install Dependencies
        run: |  
          gem install fastlane

      - name: Build IPA
        run: |  
          fastlane gym
